export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <title>Ihsan | Portfolio</title>
        <meta name="description" content="Generated by Ihsan | Portfolio" />
      </head>
      <body>{children}</body>
    </html>
  );
}
